package com.atyp.scorerecorder;


/**
 * 
 * @author dmarusca
 *
 */
public class ScoreRecorder {
	
	
	/**
	 *  Method takes an array of integer scores, and put them into binary unbalanced tree while 
     * 	counting the number of times each score is seen. The first score from the given list should occupy the 
     *  root node. 
     *      *  
	 * @param scores array of integer scores
	 * @return String representation of the tree generated by  breadth-first approach.  Scores are to be inserted into
	 *  the tree in the order that they are given.
     *  For example, if you were given the stream of scores: 4, 2, 5, 5, 6, 1, 4. That would result in the 
     *  tree with the following structure where each node is represented as <score>:<count>.
     * 	  	  4:2
     *  	  / \
     *  		2:1 5:2
     *  		/     \
     *  	  1:1     6:1
     *      When serialized this tree is represented by the string: 4:2, 2:1, 5:2, 1:1, , , 6:1
     *      Each <score>:<count> entry is delimited with a comma. Empty children with a sibling do not output 
     *     anything, but retain the comma delimiter.

	 */
	public String arrayToTree(Integer[] scores) {
		return null;
		
	}

}
